### ISSUE TITLE
Errors During npm install

### ISSUE THREAD

**Issue by Dresch360** [shbatm/MMM-KeyBindings#19]
**Describe the bug**
Every time I attempt npm install I get errors

If you are having an actual issue, please include a clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**
The modules to install

**Configuration**
Please include:
Pi4
MM Version 2.20.0
OS: 
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

* It may be easier to post these in a [Gist](https://gist.github.com) and post the link here.

**Logs**

**Additional context**
m ERR! code 1
npm ERR! path /home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev
npm ERR! command failed
npm ERR! command sh /tmp/install-f5847f38.sh
npm ERR! make: Entering directory '/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build'
npm ERR!   CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
npm ERR!   AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   CXX(target) Release/obj.target/udev/main.o
npm ERR! make: Leaving directory '/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build'
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm/udev.node --module_name=udev --module_path=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.17.1 | linux | arm
npm ERR! node-pre-gyp info check checked for "/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm/udev.node" (not found)
npm ERR! node-pre-gyp http GET https:///node-v93-linux-arm.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://node-v93-linux-arm.tar.gz/ failed, reason: getaddrinfo ENOTFOUND node-v93-linux-arm.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for udev@1.0.1 and node@16.17.1 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error request to https://node-v93-linux-arm.tar.gz/ failed, reason: getaddrinfo ENOTFOUND node-v93-linux-arm.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | arm
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/pi/.cache/node-gyp/16.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/16.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/16.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.1 | linux | arm
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../main.cc:3:
npm ERR! ../udev.h:3:10: fatal error: libudev.h: No such file or directory
npm ERR!     3 | #include <libudev.h>
npm ERR!       |          ^~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [udev.target.mk:113: Release/obj.target/udev/main.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.61-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm/udev.node" "--module_name=udev" "--module_path=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm/udev.node --module_name=udev --module_path=/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev/build/node-v93-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 5.15.61-v7l+
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/udev
npm ERR! node-pre-gyp ERR! node -v v16.17.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-14T13_54_49_788Z-debug-0.log

If you are not comfortable posting the logs or configuration on a public place, you may also send @shbatm a private chat on the [MagicMirror² Forum](https://forum.magicmirror.builders) or send an e-mail to support@shbatm.com.  E-mails asking general questions or without an accompanying Issue will not be answered.

**Comment by KristjanESPERANTO** [comment]
With release of 1.3.5 this shouldn't not be an issue anymore 🙂

**Comment by KristjanESPERANTO** [comment]
@piccolo456 Thanks for reporting. I replaced the problematic dependency `udev` with a modern alternative (`usb`) and just released version 1.3.12 of the module. Please check out the new version 🙂

**Comment by piccolo456** [comment]
Thanks for updating, it seem like there is another error (or a user error)


> mmm-keybindings@1.3.12 postinstall
> ./postinstall.sh

Get the version of electron used by MagicMirror and rebuild native packages

An unhandled error occurred inside electron-rebuild
The "paths[0]" argument must be of type string. Received undefined

_TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1101:7)
    at file:///home/orangepi/MagicMirror/modules/MMM-KeyBindings/node_modules/@electron/rebuild/lib/cli.js:73:30_

> mmm-keybindings@1.3.12 prepare
> [ -f node_modules/.bin/husky ] && husky || true


added 199 packages, and audited 200 packages in 49s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by KristjanESPERANTO** [comment]
@piccolo456 That's interesting.

What happens when you run this:

```bash
cd ~/MagicMirror
cat ./node_modules/electron/package.json | grep version
```

The output should look like this:
```bash
  "version": "37.2.3"
```

Which MagicMirror version and which node version do you have? You can run this to get the info:

```bash
cd ~/MagicMirror
cat package.json | grep version
node -v
```

The output should look like this:
```bash
	"version": "2.33.0-develop",
v24.4.0
```

You should not have the same version numbers since I'm working on the develop branch.

**Comment by KristjanESPERANTO** [comment]
Yes, you should update node and MagicMirror to the current version.

**Comment by piccolo456** [comment]
Updated and all work now, Thanks.
